controllers/EmployeesController.php
<?php

namespace app\controllers;

use app\models\EmployeesAttach;
use app\models\EmployeesChildren;
use app\models\EmployeesMove;
use app\models\EmployeesStatus;
use app\models\forms\AttachForm;
use app\models\forms\RoutePerDateForm;
use app\models\RouteAddress;
use app\models\search\EmployeesPaysSearch;
use app\models\search\RoutesSearch;
use Yii;
use app\models\Employees;
use app\models\search\EmployeesSearch;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use \yii\web\Response;
use yii\helpers\Html;
use yii\web\UploadedFile;

/**
 * EmployeesController implements the CRUD actions for Employees model.
 */
class EmployeesController extends Controller
{

    public function behaviors()
    {
        return [
            'access' => [
                'class' => \yii\filters\AccessControl::className(),

                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
//                        'matchCallback' => function ($rule, $action) {
//                            if (!Yii::$app->user->identity->isSuperAdmin()) {
//                                return $this->redirect(['/']);
//                            }
//                            return true;
//
//                        },
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                    'bulk-delete' => ['post'],
                ],
            ],
        ];
    }

    public function actionIndex()
    {
        $searchModel = new EmployeesSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * @param $id
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionView($id)
    {
//        $request = Yii::$app->request;
        $model = $this->findModel($id);
        $routeModel = new RoutePerDateForm();
        $attachPassport = EmployeesAttach::find()->where(['employees_id'=>$id,'category_file'=>1])->all();
        $attachOther = EmployeesAttach::find()->where(['employees_id'=>$id,'category_file'=>2])->all();
        $children = EmployeesChildren::find()->where(['employees_id'=>$id])->all();
        $statuses = EmployeesStatus::find()->where(['employees_id'=>$id])->all();

        $paySearch = new EmployeesPaysSearch();
        $paySearch->employeeId = $id;
        $payDataProvider = $paySearch->search([]);

        $searchModelReportFact = new RoutesSearch();
        $dataProviderReportFact = $searchModelReportFact->searchReportFact([]);
        $dataProviderReportFact->query->andWhere(['employees_id' => $id]);

        return $this->render('view', [
            'model' => $model,
            'attachPassport' => $attachPassport,
            'attachOther' => $attachOther,
            'routeModel' => $routeModel,
            'children' => $children,
            'statuses' => $statuses,
            'paySearch' => $paySearch,
            'payDataProvider' => $payDataProvider,
            'searchModelReportFact' => $searchModelReportFact,
            'dataProviderReportFact' => $dataProviderReportFact,
        ]);
    }

    public function actionViewMainAjax($id)
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $model = $this->findModel($id);

        return [
            'content' => $this->renderAjax('view_main_ajax', [
                'model' => $model,
            ])
        ];
    }

    /**
     * @return string|Response
     * @throws \Exception
     * @throws \Throwable
     * @throws \yii\base\Exception
     * @throws \yii\db\StaleObjectException
     */
    public function actionCreate()
    {
        $request = Yii::$app->request;
        $model = new Employees();
        if ($model->load($request->post()) && $model->save()) {
            $model->main_photo = UploadedFile::getInstance($model, 'main_photo');
            $main_path = "images/photo/";
            if (!empty($model->main_photo)) {
                if (!file_exists(($main_path))) {
                    mkdir($main_path, 0777, true);
                }
                $main_photo = $main_path . time() . Yii::$app->security->generateRandomString(5) . '.' . $model->main_photo->extension;
                $model->main_photo->saveAs($main_photo);
                $model->foto = '/'.$main_photo;
                $model->save();
            }
            //загрузка паспортов .
            $model->saveAttachPassport();
            //загрузка других .
            $model->saveAttachOther();
            //Сохранить список детей
            $model->children = $request->post('Employees')['children'];
            $model->saveChildren();
            return $this->redirect(['index', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }

    }

    /**
     * @param $id
     * @return string|Response
     * @throws NotFoundHttpException
     * @throws \Exception
     * @throws \Throwable
     * @throws \yii\base\Exception
     * @throws \yii\db\StaleObjectException
     */
    public function actionUpdate($id)
    {
        $request = Yii::$app->request;
        $model = $this->findModel($id);
        $queryPassport = EmployeesAttach::find()->where(['employees_id'=>$id,'category_file'=>1]);
        $dataProviderPassport = new ActiveDataProvider(['query' => $queryPassport]);
        $queryOther = EmployeesAttach::find()->where(['employees_id'=>$id,'category_file'=>2]);
        $dataProviderOther = new ActiveDataProvider(['query' => $queryOther]);
        $model->children = EmployeesChildren::find()->where(['employees_id'=>$id])->asArray()->all();

        if ($model->load($request->post()) && $model->save()) {
            $model->main_photo = UploadedFile::getInstance($model, 'main_photo');
            $main_path = "images/photo/";
            if (!empty($model->main_photo)) {
                if (!file_exists(($main_path))) {
                    mkdir($main_path, 0777, true);
                }
                $main_photo = $main_path . time() . Yii::$app->security->generateRandomString(5) . '.' . $model->main_photo->extension;
                $model->main_photo->saveAs($main_photo);
                $model->foto = '/'.$main_photo;
                $model->save();
            }

            //загрузка паспортов .
            $model->saveAttachPassport();
            //загрузка других .
            $model->saveAttachOther();
            //Сохранить список детей
            $model->children = $request->post('Employees')['children'];
            $model->saveChildren();


            return $this->redirect(['index']);
        } else {
            return $this->render('update', [
                'model' => $model,
                'dataProviderPassport' => $dataProviderPassport,
                'dataProviderOther' => $dataProviderOther,

            ]);
        }
    }

    /**
     * @param $id
     * @return array|Response
     * @throws NotFoundHttpException
     * @throws \Exception
     * @throws \Throwable
     * @throws \yii\db\StaleObjectException
     */
    public function actionDelete($id)
    {
        $request = Yii::$app->request;
        $this->findModel($id)->delete();

        if($request->isAjax){
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ['forceClose'=>true,'forceReload'=>'#crud-datatable-pjax'];
        }else{
            return $this->redirect(['index']);
        }


    }

    /**
     * @param $category
     * @param $id
     * @return array|Response
     * @throws \Exception
     * @throws \Throwable
     * @throws \yii\db\StaleObjectException
     */
    public function actionAttachDelete($category, $id)
    {
        $request = Yii::$app->request;
        EmployeesAttach::findOne($id)->delete();
        if($request->isAjax){
            Yii::$app->response->format = Response::FORMAT_JSON;
            if ($category ==1) {
                return ['forceClose'=>true,'forceReload'=>'#crud-datatable-passport-pjax'];
            } else {
                return ['forceClose'=>true,'forceReload'=>'#crud-datatable-other-pjax'];
            }

        }else{
            return $this->redirect(['index']);
        }


    }

    /**
     * @param $category
     * @param $id
     * @return array|string|Response
     */
    public function actionAttachAdd($category,$id)
    {
        $request = Yii::$app->request;
        $model = new AttachForm();
        if ($request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            if ($request->isGet) {
                return [
                    'title' => "Добавить вложения",
                    'content' => $this->renderAjax('_form-attach', [
                        'model' => $model,
                    ]),
                    'footer' => Html::button('Закрыть', ['class' => 'btn btn-primary pull-left', 'data-dismiss' => "modal"]) .
                        Html::button('Сохранить', ['class' => 'btn btn-info', 'type' => "submit"])
                ];
            }else if($model->load($request->post())){
                $model->saveAttach($category,$id);
                if ($category ==1) {
                    return ['forceClose'=>true,'forceReload'=>'#crud-datatable-passport-pjax'];
                } else {
                    return ['forceClose'=>true,'forceReload'=>'#crud-datatable-other-pjax'];
                }
            }else{
                return [
                    'title' => "Добавить вложения",
                    'content' => $this->renderAjax('_form-attach', [
                        'model' => $model,

views/employees/_columns-attach.php
<?php

use app\helpers\StatusHelper;
use app\models\Employees;
use yii\helpers\Url;

return [
    [
        'class' => 'kartik\grid\CheckboxColumn',
        'width' => '20px',
    ],
    [
        'class' => 'kartik\grid\SerialColumn',
        'width' => '30px',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'file',
    ],


    [
        'class' => 'kartik\grid\ActionColumn',
        'header' =>"&nbsp&nbsp&nbspДействия&nbsp&nbsp&nbsp",
        'dropdown' => false,
        'vAlign'=>'middle',
        'urlCreator' => function($action, $model, $key, $index) { 
                return Url::to([$action,'id'=>$key]);
        },
        'viewOptions'=>['label'=>'<button class="btn btn-info btn-xs"><span class="glyphicon glyphicon-eye-open"></span></button>','role'=>'modal-remote'],
        'updateOptions'=>['label'=>'<button class="btn btn-warning btn-xs"><span class="glyphicon glyphicon-pencil"></span></button>','data-pjax'=>0,'title'=>'Изменить', 'data-toggle'=>'tooltip'],
        'deleteOptions'=>['role'=>'modal-remote','title'=>'Удалить',
            'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
            'data-request-method'=>'post',
            'label'=>'<button class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-trash"></span></button>',
            'data-toggle'=>'tooltip',
            'data-confirm-title'=>'Вы уверенны?',
            'data-confirm-message'=>'Вы действительно хотите удалить запись '],
],

];   

views/employees/_columns.php
<?php

use app\helpers\StatusHelper;
use app\models\Employees;
use app\models\EmployeesPosition;
use yii\helpers\Html;
use yii\helpers\Url;

return [
    [
        'class' => 'kartik\grid\CheckboxColumn',
        'width' => '20px',
    ],
    [
        'class' => 'kartik\grid\SerialColumn',
        'width' => '30px',
    ],
    // [
    // 'class'=>'\kartik\grid\DataColumn',
    // 'attribute'=>'foto',
    // ],
    // [
    // 'class'=>'\kartik\grid\DataColumn',
    // 'attribute'=>'id',
    // ],
//    [
//        'class'=>'\kartik\grid\DataColumn',
//        'attribute'=>'manager_id',
//    ],
    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'status',
        'value' => function ($model) {
            return $model->getCurrentStatus();
        },
        'filter' => Employees::getStatuses(),
        'contentOptions' => ['style' => 'width:150px; text-align:center'],


    ],
    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'position_id',
        'value' => function ($model) {
            return $model->position->name;
        },
        'filter' => EmployeesPosition::getPositionList(),
    ],
    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'fio',
        'label' => 'ФИО',
        'value' => function (Employees $model) {
            return Html::a($model->fio ?? null, ['/employees/view', 'id' => $model->id]);
        },
        'format' => 'raw',
    ],
//    [
//        'class' => '\kartik\grid\DataColumn',
//        'attribute' => 'lastname',
//    ],
//    [
//        'class' => '\kartik\grid\DataColumn',
//        'attribute' => 'firstname',
//    ],
    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'address',
    ],
    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'family_status',
        'value' => function ($model) {
            return $model->getCurrentFamilyStatus();
        },
        'filter' => Employees::getFamilyStatuses(),
        'contentOptions' => ['style' => 'width:100px; text-align:center'],
    ],
    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'phone',
    ],

    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'email',
    ],

    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'code_structure',
    ],

    [
        'class' => 'kartik\grid\ActionColumn',
        'header' => "&nbsp&nbsp&nbspДействия&nbsp&nbsp&nbsp",
        'dropdown' => false,
        'vAlign' => 'middle',
        'urlCreator' => function ($action, $model, $key, $index) {
            return Url::to([$action, 'id' => $key]);
        },
        'viewOptions' => [
            'label' => '<button class="btn btn-info btn-xs"><span class="glyphicon glyphicon-eye-open"></span></button>',
            'data-pjax' => 0,
        ],
        'updateOptions' => [
            'label' => '<button class="btn btn-warning btn-xs"><span class="glyphicon glyphicon-pencil"></span></button>',
            'data-pjax' => 0,
            'title' => 'Изменить',
            'data-toggle' => 'tooltip'
        ],
        'deleteOptions' => [
            'role' => 'modal-remote',
            'title' => 'Удалить',
            'data-confirm' => false,
            'data-method' => false,// for overide yii data api
            'data-request-method' => 'post',
            'label' => '<button class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-trash"></span></button>',
            'data-toggle' => 'tooltip',
            'data-confirm-title' => 'Вы уверенны?',
            'data-confirm-message' => 'Вы действительно хотите удалить запись '
        ],
    ],

];   

views/employees/_form-attach.php
<?php

use kartik\widgets\FileInput;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Employees */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="employees-form-attach">

    <?php $form = ActiveForm::begin([
        'options' => [
            'method' => 'post',
            'enctype' => 'multipart/form-data',
            ]
    ]); ?>
    <?=$form->field($model, 'files[]')->widget(FileInput::classname(), [
        'options'=>[
            'multiple'=>true,
        ],
        'pluginOptions' => [
            //'hideThumbnailContent'=> true,
            'overwriteInitial'=>true,
            'showUpload' => false,
            'browseLabel' => '',
            'maxFileSize'=>2800,
            //'theme' => "explorer",
        ]
    ])->label(false);?>
    <?php ActiveForm::end(); ?>
    
</div>

views/employees/_form-create.php
<?php

use app\models\Employees;
use app\models\EmployeesCategory;
use app\models\EmployeesPosition;
use kartik\date\DatePicker;
use kartik\widgets\FileInput;
use kartik\widgets\Select2;
use unclead\multipleinput\MultipleInput;
use unclead\multipleinput\MultipleInputColumn;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Employees */
/* @var $form yii\widgets\ActiveForm */
?>

<style>
    .modal-lg {
        width: 1200px;
    }
    .form-group {
        margin-bottom: 0px;
    }
    samp {
        display: none;
    }
    .file-thumbnail-footer {
        display: none;
    }
    .form-group-sm .form-control {
        height: 27px;
    }
    .form-group-sm select.form-control {
        height: 27px;
    }

    .help-block {
        margin: 0px;
    }
    label {
        font-size: 12px;
        margin-bottom: 0px;
    }
    .file-drop-zone-title {
        padding: 55px 10px;
    }
    .input-group-addon {
        padding: 0px 6px;
    }

</style>
<div class="employees-form">

    <?php $form = ActiveForm::begin([
        'options' => [
            'method' => 'post',
            'enctype' => 'multipart/form-data',
            ]
    ]); ?>
    <div class="row">
        <div class="form-group">
            <?= Html::a( 'Отмена', \yii\helpers\Url::to(['/employees/index']), ['class' => 'btn btn-danger pull-right']) ?>
            <?= Html::submitButton('Создать', ['class' => 'btn btn-primary  pull-right']) ?>

        </div>
    </div>

    <div class="row">
        <div class="col-md-8 bg-info">
            <h5>Персональные данные</h5>
        </div>
        <div class="col-md-4 bg-info">
            <h5>Паспортные данные</h5>
        </div>

    </div>
    <div class="row form-group form-group-sm">
        <div class="col-md-4">
            <?= $form->field($model, 'status')->dropDownList(Employees::getStatuses()) ?>
            <?= $form->field($model, 'position_id')->dropDownList(EmployeesPosition::getPositionList())?>
            <?= $form->field($model, 'lastname')->textInput(['maxlength' => true]) ?>
            <?= $form->field($model, 'firstname')->textInput(['maxlength' => true]) ?>
            <?= $form->field($model, 'parentname')->textInput(['maxlength' => true]) ?>
            <?= $form->field($model, 'birthday')->widget(DatePicker::classname(), [
                'type' => DatePicker::TYPE_COMPONENT_APPEND,
                'pickerIcon' => '<i class="glyphicon glyphicon-calendar text-primary"></i>',
                'removeIcon' => '<i class="glyphicon glyphicon-trash text-danger"></i>',
                'pluginOptions' => [
                    'autoclose'=>true,
                    'format' => 'yyyy-mm-dd',
                ]
            ]); ?>
            <?= $form->field($model, 'family_status')->dropDownList(Employees::getFamilyStatuses()) ?>
            <?= $form->field($model, 'children')->widget(MultipleInput::className(), [
                'columns' => [
                    [
                        'name'  => 'name',
                        'title' => 'Имя ребенка',
                    ],
                    [
                        'name'  => 'birthday',
                        'type'  => \kartik\date\DatePicker::className(),
                        'title' => 'День рождения',
                        'options' => [
                            'type' => DatePicker::TYPE_COMPONENT_APPEND,
                            'pickerIcon' => '<i class="glyphicon glyphicon-calendar text-primary"></i>',
                            'removeIcon' => '<i class="glyphicon glyphicon-trash text-danger"></i>',
                            'pluginOptions' => [
                                'autoclose'=>true,
                                'format' => 'yyyy-mm-dd',
                            ]
                        ]
                    ],
                    [
                        'name'  => 'sex',
                        'type'  => 'dropDownList',
                        'title' => 'Пол',
                        'defaultValue' => 1,
                        'items' => [
                            1 => 'Мужской',
                            2 => 'Женский'
                        ]
                    ],

                ],
                'min'               => 0, // should be at least 2 rows
                'allowEmptyList'    => false,
                'enableGuessTitle'  => true,
                'addButtonPosition' => MultipleInput::POS_HEADER, // show add button in the header
            ])->label(false);?>
        </div>
        <div class="col-md-4">
            <?= $form->field($model, 'address')->textarea(['rows'=>2, 'maxlength' => true]) ?>
            <?= $form->field($model, 'phone')->textInput(['maxlength' => true]) ?>
            <?= $form->field($model, 'phone_add')->textInput(['maxlength' => true]) ?>
            <?= $form->field($model, 'phone_guarantor')->textInput(['maxlength' => true]) ?>
            <?= $form->field($model, 'FIO_guarantor')->textInput(['maxlength' => true]) ?>
            <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>
            <?= $form->field($model, 'phone_model')->textInput(['maxlength' => true]) ?>
            <?= $form->field($model, 'phone_id')->textInput(['maxlength' => true]) ?>

        </div>
        <div class="col-md-4">

            <?= $form->field($model, 'start_work')->widget(DatePicker::classname(), [
                'type' => DatePicker::TYPE_COMPONENT_APPEND,
                'pickerIcon' => '<i class="glyphicon glyphicon-calendar text-primary"></i>',
                'removeIcon' => '<i class="glyphicon glyphicon-trash text-danger"></i>',
                'pluginOptions' => [
                    'autoclose'=>true,
                    'format' => 'yyyy-mm-dd'
                ]
            ]); ?>
            <?= $form->field($model, 'pasport_number')->textInput(['maxlength' => true]) ?>
            <?= $form->field($model, 'pasport_publish')->textInput(['maxlength' => true]) ?>
            <?= $form->field($model, 'pasport_date')->widget(DatePicker::classname(), [
                'type' => DatePicker::TYPE_COMPONENT_APPEND,
                'pickerIcon' => '<i class="glyphicon glyphicon-calendar text-primary"></i>',
                'removeIcon' => '<i class="glyphicon glyphicon-trash text-danger"></i>',
                'pluginOptions' => [
                    'autoclose'=>true,
                    'format' => 'yyyy-mm-dd'
                ]
            ]); ?>
            <?= $form->field($model, 'code_structure')->textInput(['maxlength' => true]) ?>
            <?= $form->field($model, 'specializations')->widget(select2::classname(), [
                'data' => Employees::$specializationList,
                'options' => [
                    'placeholder' => 'Выберите специализации ...',
                    'multiple' => true
                ],
            ]); ?>
            <?= $form->field($model, 'other_data')->textarea(['rows'=>2, 'maxlength' => true]) ?>

        </div>
    </div>
    <div class="row">
        <div class="col-md-4 bg-info">
            <h5>Фото </h5>
        </div>
        <div class="col-md-4 bg-info">
            <h5>Сканы паспорта</h5>
        </div>
        <div class="col-md-4 bg-info">
            <h5>Прочие файлы</h5>
        </div>

    </div>
<div class="row">
    <div class="col-md-4">
        <?= $form->field($model, 'main_photo')->widget(FileInput::classname(), [
            'options'=>[
                'multiple'=>false,
                'accept' => 'image/*',
            ],
            'pluginOptions' => [
                'overwriteInitial'=>true,
                'showUpload' => false,
                'browseLabel' => '',
                'removeLabel' => '',
                'maxFileSize'=>2800,

            ]
        ])->label(false);?>
    </div>
    <div class="col-md-4">
        <?= $form->field($model, 'pasport_files[]')->widget(FileInput::classname(), [
            'options'=>[
                'multiple'=>true,
            ],
            'pluginOptions' => [
                'hideThumbnailContent'=> true,
                'overwriteInitial'=>true,
                'showUpload' => false,
                'browseLabel' => '',
                'maxFileSize'=>2800,
                'theme' => "explorer",
            ]
        ])->label(false);?>
    </div>
    <div class="col-md-4 ">
        <?= $form->field($model, 'other_files[]')->widget(FileInput::classname(), [
            'options'=>[
                'multiple'=>true,
            ],
            'pluginOptions' => [
                'hideThumbnailContent'=> true,
                'overwriteInitial'=>true,
                'showUpload' => false,
                'browseLabel' => '',
                'maxFileSize'=>2800,
                'theme' => "explorer",
            ]
        ])->label(false); ?>
    </div>

</div>
    <?php ActiveForm::end(); ?>
    
</div>

views/employees/_view_pays.php
<?php

use kartik\grid\GridView;

/** @var $this \yii\web\View */
/** @var $searchModel \app\models\search\EmployeesPaysSearch */
/** @var $dataProvider \yii\data\ArrayDataProvider*/


$placements = \yii\helpers\ArrayHelper::map(\app\models\PlacementMethod::find()->all(), 'id', 'name');

$placementsColumns = [];

foreach ($placements as $id => $name){
    $placementsColumns[] = [
        'label' => "КР «{$name}»",
        'value' => "p-{$id}",
    ];
}


$columns = [
    [
        'attribute' => 'projectId',
        'label' => 'Проект',
        'value' => 'project_name'
    ],
    [
        'label' => 'Фактическое кол-во',
        'value' => 'fact_count'
    ],
    [
        'label' => 'Подтвержденное кол-во',
        'value' => 'completed_count',
    ],
    [
        'label' => 'Рабочих часов',
        'value' => 'workHours',
    ]
];

$columns = \yii\helpers\ArrayHelper::merge($columns, $placementsColumns);

$columns = \yii\helpers\ArrayHelper::merge($columns, [
    [
        'label' => 'Сумма штрафов',
        'value' => 'completed_count',
        'format' => ['currency', 'rub'],
        'hAlign' => GridView::ALIGN_CENTER,
    ],
    [
        'label' => 'Оплата',
        'value' => 'payment_amount',
        'format' => ['currency', 'rub'],
        'hAlign' => GridView::ALIGN_CENTER,
    ],
]);

?>

<div class="row">
    <div class="col-md-12">
        <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'columns' => $columns,
            'striped' => true,
            'condensed' => true,
            'responsive' => true,
            'panel' => [
                'type' => 'primary',
                'heading' => '<i class="glyphicon glyphicon-list"></i>Отчет по зарплатам',
                'before'=>'',
                'after'=>'',
            ]
        ]) ?>
    </div>
</div>

views/employees/_view_route.php
<?php

use kartik\widgets\DatePicker;
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Employees */
/* @var $routeModel app\models\Employees */
?>
<div class="employees-view-route">

    <div class="row">
        <div class="col-md-2">
            <div class="row">
                <?php $form = ActiveForm::begin(['id' => 'employees-route'
                ]); ?>
                <div class="col-md-12 bg-info">
                    <h5>Фильтр</h5>
                    <?= $form->field($routeModel, 'start_date')->textInput(['type'=>'date','onChange'=>'selectRouteList()']); ?>
                    <?= $form->field($routeModel, 'end_date')->textInput(['type'=>'date']);?>
                    <?= $form->field($routeModel, 'route')->dropDownList(\app\models\Routes::getRouteFromEmployee($model->id)) ?>
                    <div class="row">
                        <div class="col-md-12">
                            <?= \yii\helpers\Html::a('<span class="btn btn-primary">Сформировать карту</span>', "#",['onClick'=>'getEmployeeRoute()']) ?>

                        </div>
                    </div>

                </div>
                <?php ActiveForm::end() ?>
            </div>
        </div>
        <div class="col-md-10">
            <div id="playPanel" class="row" style="display: none">
                <div class="col-xs-1">
                    <?=Html::img('/images/yandex/start.png',['onClick'=>'play()','id'=>'play','style'=>'margin-top:20px']);?>
                </div>
                <div class="col-xs-11">
                    <input type="text" id="example_id" name="example_name" value="" />
                </div>
            </div>
            <div class="row">
                <div id="map">
                </div>
            </div>
        </div>
    </div>

</div>

<style>
    #map {
        width: 100%; height: 600px; padding: 0; margin: 0;
    }
</style>
<style>
    .YMaps-layer-container img{
        max-width: none;
    }
</style>
<?php

$script = <<<JS
var employeeId = $model->id,
center_map = [55.750625, 37.626];
JS;
$this->registerJs($script, yii\web\View::POS_HEAD);
$this->registerCssFile("https://cdnjs.cloudflare.com/ajax/libs/ion-rangeslider/2.3.0/css/ion.rangeSlider.min.css");
$this->registerJsFile("https://cdnjs.cloudflare.com/ajax/libs/ion-rangeslider/2.3.0/js/ion.rangeSlider.min.js",['depends' => [\yii\web\JqueryAsset::className()]]);
$this->registerJsFile("https://api-maps.yandex.ru/2.1/?lang=ru_RU&amp;apikey=&lt;ваш API-ключ&gt;", ['depends' => [\yii\web\JqueryAsset::className()]]);
$this->registerJsFile("/js/employee_map.js", ['depends' => [\yii\web\JqueryAsset::className()]]);
?>

views/employees/add-attach.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Employees */

?>
<div class="employees-create">
    <?= $this->render('_form-attach', [
        'model' => $model,
    ]) ?>
</div>

views/employees/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Employees */

?>
<div class="employees-create">
    <?= $this->render('_form-create', [
        'model' => $model,
    ]) ?>
</div>