models/Projects.php
<?php

namespace app\models;

use yii\db\ActiveRecord;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "projects".
 *
 * @property int $id
 * @property string $name Название
 * @property int $client_id Заказчик
 * @property string $date_start Дата начала
 * @property string $date_end Дата окончания
 *
 * @property double $honestyPercent
 * @property int $daysDuration
 *
 * @property Clients $client
 * @property float $project_cost
 * @property ProjectsPlacement[] $projectsPlacements
 * @property Routes[] $routes
 */
class Projects extends ActiveRecord
{
    /**
     * @var string
     */
    public $intervalDates;

    public $placements;

    public $maketFile;

    public $prices;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'projects';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['client_id', 'normal_one', 'price_id'], 'integer'],
            [['name', 'maket'], 'string', 'max' => 255],
            [
                ['client_id'],
                'exist',
                'skipOnError' => true,
                'targetClass' => Clients::className(),
                'targetAttribute' => ['client_id' => 'id']
            ],
            [
                ['route_template_id'],
                'exist',
                'skipOnError' => true,
                'targetClass' => RouteTemplates::className(),
                'targetAttribute' => ['route_template_id' => 'id']
            ],
            [['intervalDates', 'info_add', 'maket_file', 'date_start', 'date_end', 'prices'], 'safe'],
            //[['maketFile'], 'file', 'skipOnEmpty' => false],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function afterFind()
    {
        parent::afterFind();
    }

    /**
     * @return double
     */
    public function getHonestyPercent()
    {
        $routes = $this->routes;
        $completedCount = array_sum(ArrayHelper::getColumn($routes,'completed_count'));
        $factCountAddress = array_sum(ArrayHelper::getColumn($routes, 'fact_count_adress'));
        return round($completedCount*100/$factCountAddress, 2);
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Проeкт',
            'client_id' => 'Заказчик',
            'project_cost' => 'Общая сумма',
            'date_start' => 'Дата начала',
            'date_end' => 'Дата окончания',
            'intervalDates' => 'Дата начала — Дата завершения',
            'normal_one' => 'Норма на одного промоутера',
            'maket' => 'Макет',
            'maket_file' => 'Файл макета',
            'info_add' => 'Доплнительная информация',
            'price_id' => 'Цена',
            'prices' => 'Цены',
            'route_template_id' => 'Шаблон маршрутного листа',
        ];
    }

    /**
     * Получить длительность выполнения в днях
     * @return int
     */
    public function getDaysDuration()
    {
        $startTimestamp = strtotime($this->date_start);
        $endTimestamp = strtotime($this->date_end);

        return round(($endTimestamp - $startTimestamp) / 86400);
    }

    /**
     * Получить длительность выполнения в днях
     * @return int
     */
    public function getDaysDurationPeriod($start, $end)
    {
        $startTimestamp = strtotime($start);
        $endTimestamp = strtotime($end);

        return round(($endTimestamp - $startTimestamp) / 86400);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getClient()
    {
        return $this->hasOne(Clients::class, ['id' => 'client_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProjectsPlacements()
    {
        return $this->hasMany(ProjectsPlacement::className(), ['project_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRoutes()
    {
        return $this->hasMany(Routes::className(), ['project_id' => 'id']);
    }


    /**
     * Связь шаблона маршрута с маршрутом
     * @return \yii\db\ActiveQuery
     */
    public function getRouteTemplates()
    {
        return $this->hasOne(RouteTemplates::className(), ['id' => 'route_template_id']);
    }

    public function savePlacements($id = null)
    {
        if ($id) {
            $model = ProjectsPlacement::find()->where(['id' => $id])->one();
            if (!$model) {
                $model = new ProjectsPlacement();
            }
        } else {
            $model = new ProjectsPlacement();
        }
        $prices = Prices::find()->indexBy('id')->all();
        $all_cost = 0;
        $model->project_id = $this->id;
        $model->placement_id = $this->placements->placement_id;
        $model->price_id = $this->placements->price_id;
        $model->price = $prices[$this->placements->price_id]->price;
        $model->circulation = $this->placements->circulation;
        $all_cost += $model->price * $this->placements->circulation;
        $model->save();
        //$this->project_cost = $all_cost;
        //$this->save();
    }

    /**
     * @return bool
     * @throws \Exception
     * @throws \Throwable
     * @throws \yii\db\StaleObjectException
     */
    public function beforeDelete()
    {
        $routes = Routes::find()->where(['project_id' => $this->id])->all();
        foreach ($routes as $route) {
            $route->delete();
        }
        ProjectsPlacement::deleteAll(['project_id' => $this->id]);
        ProjectAddress::deleteAll(['project_id' => $this->id]);
        Zones::deleteAll(['project_id' => $this->id]);
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    /**
     * @param bool $insert
     * @param array $changedAttributes
     */
    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes);

        if($this->prices != null){
            PricesProjects::deleteAll(['projects_id' => $this->id]);
            foreach ($this->prices as $price)
            {
                (new PricesProjects(['projects_id' => $this->id, 'prices_id' => $price]))->save();
            }
        }
    }

    /**
     *
     */
    public function getAllAddresses()
    {
        $addresses = [];

        foreach ($this->routes as $route) {
            $adrs = $route->addressLists;
            $addresses = array_merge($addresses, $adrs);
        }

        return $addresses;
    }

    public function getAllRoutes()
    {
        return $this->routes;
    }

    public function createCopy($form, $oldProject)
    {
        if ($form['placementMethod'] == 1) {
            $placementMethods = ProjectsPlacement::find()->where(['project_id' => $oldProject])->all();
            foreach ($placementMethods as $placementMethod) {
                $new = new ProjectsPlacement();
                $new->attributes = $placementMethod->attributes;
                $new->project_id = $this->id;
                $new->save();
            }
        }
        if ($form['addresslist'] == 1) {
            $addresslists = ProjectAddress::find()->where(['project_id' => $oldProject])->all();
            foreach ($addresslists as $addresslist) {
                $new = new ProjectAddress();
                $new->attributes = $addresslist->attributes;
                $new->project_id = $this->id;
                $new->save();
            }
        }
        if ($form['zones'] == 1) {
            $zones = Zones::find()->where(['project_id' => $oldProject])->all();
            foreach ($zones as $zone) {
                $new = new Zones();
                $new->attributes = $zone->attributes;
                $new->project_id = $this->id;
                $new->save();
            }
        }
        if ($form['routes'] == 1 && $form['addresslist'] == 1) {
            $routes = Routes::find()->where(['project_id' => $oldProject])->all();
            foreach ($routes as $route) {
                $new = new Routes();
                $new->attributes = $route->attributes;
                $new->project_id = $this->id;
                $new->save();
                $routeAddress = RouteAddress::find()->where(['route_id' => $route->id])->all();
                foreach ($routeAddress as $address) {
                    $newItem = new RouteAddress();
                    $newItem->attributes = $address->attributes;
                    $newItem->route_id = $new->id;
                    $newItem->save();
                }
            }
        }
    }
}

views/projects/_columns-route-address.php
<?php

use yii\bootstrap\Html;
use yii\helpers\Url;

$fines = \yii\helpers\ArrayHelper::map(\app\models\Fines::find()->all(), 'id', 'name');

return [
    [
        'class' => 'kartik\grid\CheckboxColumn',
        'width' => '20px',
    ],
    [
        'class' => 'kartik\grid\SerialColumn',
        'width' => '30px',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'address.street',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'address.house',
    ],

    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'address.housing',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'label'=>'Етажей',
        'attribute'=>'address.floor',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'label'=>'Квартир',
        'attribute'=>'address.apartament',
    ],

    [
        'class'=>'\kartik\grid\DataColumn',
        'label'=>'Подьездов',
        'attribute'=>'address.entrance',
    ],

    [
        'class'=>'\kartik\grid\DataColumn',
        'label'=>'Тип',
        'attribute'=>'address.type',
        'value'=>function ($model) {
            switch ($model->address->type) {
                case 0 : return "<i class='fa fa-building'></i>";
                case 1 : return "<i class='fa fa-building-o'></i>";
                case 2 : return "<i class='fa fa-bank'></i>";
            }


        },
        'format'=>'raw',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'label'=>'План.дата',
        'attribute'=>'plane_date',
    ],

    /*[
        'class'=>'\kartik\grid\DataColumn',
        'label' => 'Штраф',
        'attribute'=>'fine_id',
        'content' => function($model) use($fines) {
            return \kartik\editable\Editable::widget([
                'model' => $model,
                'formOptions' => [
                    'action' => Url::to(['index', 'id' => $model->id, 'attribute' => 'fine_id']),
                ],
                'attribute' => 'fine_id',
                'inputType' => \kartik\editable\Editable::INPUT_SELECT2,
                'options' => [
                    'value' => $model->fine->name,
                    'data' => $fines,
                    'pluginOptions'=>['allowClear'=>true],
                ],
            ]);
        },
    ],*/
//    [
//        'class'=>'\kartik\grid\EditableColumn',
//        'attribute'=>'completed_edition',
//        'content' => function($model) use($fines) {
//            return \kartik\editable\Editable::widget([
//                'model' => $model,
//                'attribute' => 'completed_edition',
//                'inputType' => \kartik\editable\Editable::INPUT_TEXT,
//                'options' => [
//                    'value' => $model->completed_edition,
//                    'data' => $fines,
//                    'pluginOptions'=>['allowClear'=>true],
//                ],
//                'formOptions' => [
//                    'action' => Url::to(['index', 'id' => $model->id, 'attribute' => 'completed_edition']),
//                ],
//            ]);
//        },
//        'editableOptions' => [
//            'inputType' => \kartik\editable\Editable::INPUT_TEXT,
//            'formOptions' => [
//                    'action' => Url::to(['index', 'id' => $model->id, 'attribute' => 'completed_edition']),
//                ],
//        ],
//    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'comment',
    ],
//    [
//        'class'=>'\kartik\grid\DataColumn',
//        'attribute'=>'type_work',
//    ],
//    [
//        'class'=>'\kartik\grid\DataColumn',
//        'attribute'=>'addressList.plane_work',
//        'value' => function($model){
//            return $model->plane_work  ? $model->plane_work .  Html::a('Изменить',
//                     ['set-norm','id'=>$model->id],['role'=>'modal-remote','class'=>'pull-right']): Html::a('Проставить',
//                 ['set-norm','id'=>$model->id],['role'=>'modal-remote']);
//        },
//        'format'=>'raw',
//    ],
    [
        'class' => 'kartik\grid\ActionColumn',
        'header' =>"&nbsp&nbsp&nbspДействия&nbsp&nbsp&nbsp",
        'dropdown' => false,
        'template' => '{edit-addressList} {delete}',  // the default buttons + your custom button"
        'visible' => !Yii::$app->user->identity->isClient(),
        'buttons' => [

            'edit-addressList' => function($url, $model, $key) {     // render your custom button
                    return Html::a('<button class="btn btn-warning btn-xs"><span class="glyphicon glyphicon-pencil"></span></button>',
                        ['/projects/update-address','address_id'=>$model->id],['role'=>'modal-remote']);
            },
            'delete' => function($url, $model, $key) {
                return Html::a('<button class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-trash"></span></button>',
                    ['/projects/delete-address','address_id'=>$model->id],['role'=>'modal-remote']);
            }
        ],
        'vAlign'=>'middle',
        'urlCreator' => function($action, $model, $key, $index) {
                return Url::to([$action,'id'=>$key]);
        },
        'deleteOptions'=>['role'=>'modal-remote','title'=>'Удалить',
            'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
            'data-request-method'=>'post',
            'label'=>'<button class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-trash"></span></button>',
            'data-toggle'=>'tooltip',
            'data-confirm-title'=>'Вы уверенны?',
            'data-confirm-message'=>'Вы действительно хотите удалить запись '],
],

];   

views/projects/_form-addresslist_edit.php
<?php

use app\models\AddressList;
use app\models\Zones;
use kartik\select2\Select2;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model \app\models\RoutesAddressList */
/* @var $form yii\widgets\ActiveForm */

?>

<div class="routes-form">

    <?php $form = ActiveForm::begin(); ?>
    <div class="row">
        <div class="col-md-6"><?= $form->field($model, 'entrance')->input('number') ?></div>
        <div class="col-md-6"><?= $form->field($model, 'floor')->input('number') ?></div>
    </div>
    <div class="row">
        <div class="col-md-6"><?= $form->field($model, 'apartament')->input('number') ?></div>
        <div class="col-md-6"><?= $form->field($model, 'porter')->input('number') ?></div>
    </div>
    <div class="row">
        <div class="col-md-6"><?=$form->field($model, 'type')->dropDownList(AddressList::getTypes()) ?></div>
        <div class="col-md-6"><?= $form->field($model, 'zone_id')->dropDownList(Zones::getZoneByProject($model->project_id)) ?></div>
    </div>
    <div class="row">
        <div class="col-md-12"><?= $form->field($model, 'comment')->textarea(['rows' => 5]) ?></div>
    </div>






    <?php ActiveForm::end(); ?>

</div>

views/projects/_form-route!.php
<?php

use app\models\PlacementMethod;
use app\models\Prices;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Projects */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="projects-form">

    <?php $form = ActiveForm::begin(); ?>
    <?= $form->field($model, 'placement_id')->dropDownList(PlacementMethod::getPlacementMethodList()) ?>
    <?= $form->field($model, 'price_id')->dropDownList(Prices::getPriceListFullName()) ?>
    <?= $form->field($model, 'circulation')->textInput()?>
	<?php if (!Yii::$app->request->isAjax){ ?>
	  	<div class="form-group">
	        <?= Html::submitButton($model->isNewRecord ? 'Создать' : 'Изменить', ['class' => $model->isNewRecord ? 'btn btn-primary' : 'btn btn-info']) ?>
	    </div>
	<?php } ?>

    <?php ActiveForm::end(); ?>
</div>

views/projects/_form-route_add.php
<?php

use app\models\PlacementMethod;
use app\models\Zones;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\models\Routes;

/* @var $this yii\web\View */
/* @var $model app\models\Routes */
/* @var $form yii\widgets\ActiveForm */



?>

<div class="routes-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'town')->textInput() ?>
    <?= $form->field($model, 'region')->textInput() ?>
    <?= $form->field($model, 'placement_id')->dropDownList(PlacementMethod::getPlacementMethodList()) ?>
    <?= $form->field($model, 'maket')->textInput() ?>
    <?= $form->field($model, 'normal')->textInput() ?>
    <?= $form->field($model, 'status_route')->dropDownList($model->getStatuses()) ?>
    <?= $form->field($model, 'zone_id')->dropDownList(Zones::getZoneByProject($model->project_id)) ?>
    <?= $form->field($model, 'comment_manager')->textarea(['rows' => 3]) ?>
    <?php if (!Yii::$app->request->isAjax){ ?>
        <div class="form-group">
            <?= Html::submitButton($model->isNewRecord ? 'Создать' : 'Изменить', ['class' => $model->isNewRecord ? 'btn btn-primary' : 'btn btn-info']) ?>
        </div>
    <?php } ?>

    <?php ActiveForm::end(); ?>

</div>


<style>
    .routes-form label {
        font-size: 12px;
    }
</style>

views/projects/_form-routeaddress_add.php
<?php

use app\models\Zones;
use kartik\select2\Select2;
use kartik\widgets\DatePicker;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Routes */
/* @var $form yii\widgets\ActiveForm */



?>

<div class="routes-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'address_id')->widget(Select2::className(), [
        'data' => \yii\helpers\ArrayHelper::map(\app\models\AddressList::find()->all(), 'id', 'fullAddress'),
        'pluginOptions' => [
            'placeholder' => 'Выберите объект',
            'allowClear' => true,
        ],
    ]) ?>
    <?= $form->field($model, 'plane_date')->widget(DatePicker::classname(), [
        'type' => DatePicker::TYPE_COMPONENT_APPEND,
        'pickerIcon' => '<i class="glyphicon glyphicon-calendar text-primary"></i>',
        'removeIcon' => '<i class="glyphicon glyphicon-trash text-danger"></i>',
        'pluginOptions' => [
            'autoclose'=>true,
            'format' => 'yyyy-mm-dd',
        ]
    ]); ?>
    <?= $form->field($model, 'comment')->textInput() ?>
    <?php if (!Yii::$app->request->isAjax){ ?>
        <div class="form-group">
            <?= Html::submitButton($model->isNewRecord ? 'Создать' : 'Изменить', ['class' => $model->isNewRecord ? 'btn btn-primary' : 'btn btn-info']) ?>
        </div>
    <?php } ?>

    <?php ActiveForm::end(); ?>

</div>


<style>
    .routes-form label {
        font-size: 12px;
    }
</style>

views/projects/_view-main.php
<?php

use app\models\Clients;
use app\models\RouteAddress;
use johnitvn\ajaxcrud\BulkButtonWidget;
use kartik\grid\GridView;
use yii\bootstrap\Modal;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\widgets\Pjax;
use yii\helpers\ArrayHelper;

/* @var $this yii\web\View */
/* @var $model app\models\Projects */
/* @var $form yii\widgets\ActiveForm */

if(Yii::$app->user->identity->isClient()){
    $content = '';
} else {
    $content = '<div style="margin-top:10px;">' .
        Html::a('Добавить <i class="glyphicon glyphicon-plus"></i>', ['placement-create','project_id'=>$model->id],
            ['role'=>'modal-remote','title'=> 'Добавить', 'class'=>'btn btn-info']).
        '</div>';
}

?>
<style>
    #ajaxCrudModal .modal-dialog{
        width: 800px;
    }
</style>

<div class="projects-form">
    <div class="row">

        <div class="<?= Yii::$app->user->identity->isClient() ? 'col-md-12' : 'col-md-4' ?>">
            <?php Pjax::begin(['id'=>'progectMainModal'])?>
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title"> Основная информация </h3>
                </div>
                <div class="panel-body">
                    <div class="row oglavl">
                        <div class="col-md-12">
                            <span class="emp-label"><?=$model->getAttributeLabel('id')?></span>
                            <span class="emp-value"><?=$model->id?></span>
                        </div>
                    </div>
                    <div class="row oglavl">
                        <div class="col-md-12">
                            <span class="emp-label">Статус</span>
                            <span class="emp-value"><?php
                                if (strtotime($model->date_start)>time()) {
                                    echo "Планируется";
                                } elseif (strtotime($model->date_end)>time()) {
                                    echo "Текущий";
                                } else {
                                    echo "Завершенный";
                                }
                                ?></span>
                        </div>
                    </div>

                    <div class="row oglavl">
                        <div class="col-md-12">
                            <span class="emp-label"><?=$model->getAttributeLabel('name')?></span>
                            <span class="emp-value"><?=$model->name?></span>
                        </div>
                    </div>
                    <div class="row oglavl">
                        <div class="col-md-12">
                            <span class="emp-label"><?=$model->getAttributeLabel('client_id')?></span>
                            <span class="emp-value"><?=Clients::getClientList()[$model->client_id]?></span>
                        </div>
                    </div>
                    <div class="row oglavl">
                        <div class="col-md-12">
                            <span class="emp-label">Период размещения</span>
                            <span class="emp-value"><?=$model->date_start.' по '.$model->date_end?></span>
                        </div>
                    </div>
                    <div class="row oglavl">
                        <div class="col-md-12">
                            <span class="emp-label">Тираж факт</span>
                            <span class="emp-value">
                                <?php
                                    $routesPks = ArrayHelper::getColumn(\app\models\Routes::find()->where(['project_id' => $model->id])->all(), 'id');
                                    $confirmWorkSum = RouteAddress::find()->where(['route_id' => $routesPks])->sum('confirm_work');
                                    echo $confirmWorkSum;
                                ?>
                            </span>
                        </div>
                    </div>
                    <?php if(Yii::$app->user->identity->isClient() == false): ?>
                        <div class="row oglavl">
                            <div class="col-md-12">
                                <span class="emp-label">Норма на одного промоутера</span>
                                <span class="emp-value"><?=$model->normal_one?></span>
                            </div>
                        </div>
                    <?php endif; ?>
                    <div class="row oglavl">
                        <div class="col-md-12">
                            <span class="emp-label">Макет</span>
                            <span class="emp-value"><?=$model->maket?></span>
                        </div>
                    </div>
                    <div class="row oglavl">
                        <div class="col-md-12">
                            <span class="emp-label">Файл макета</span>
                            <span class="emp-value"><?=Html::a($model->maket_file,[$model->maket_file],['download'=>true,'data-pjax'=>'0','target'=>'_blank'])?></span>
                        </div>
                    </div>
                    <?php if(Yii::$app->user->identity->isClient() == false): ?>
                        <div class="row oglavl">
                            <div class="col-md-12">
                                <span class="emp-label">Шаблон маршрутного листа</span>
                                <span class="emp-value"><?=$model->routeTemplates->name?></span>
                            </div>
                        </div>
                        <div class="row ">
                            <div class="col-md-12">
                                <strong class="">Дополнительная информация: </strong>
                                <span ><?=$model->info_add?></span>
                            </div>
                        </div>
                    <?php endif; ?>

                </div>
            </div>
                <?php if(Yii::$app->user->identity->isClient() == false): ?>
                    <div class="form-group">
                        <?= Html::a('Изменить',['update','id'=>$model->id], ['class' => 'btn btn-info','role'=>'modal-remote']) ?>
                    </div>
                <?php endif; ?>
            <?php Pjax::end()?>

        </div>


        <?php if(Yii::$app->user->identity->isClient() == false): ?>
            <div class="col-md-8">
                <div id="ajaxCrudDatatable">
                    <?=GridView::widget([
                        'id'=>'crud-datatable',
                        'dataProvider' => $dataProviderProjectsPlacement,
                        'filterModel' => $searchModelProjectsPlacement,
                        'pjax'=>true,
                        'columns' => require(__DIR__.'/_columnsProjectsPlacement.php'),
                        'showPageSummary' => true,
                        'toolbar'=> [
                            ['content'=> $content,
                            ],
                        ],
                        'striped' => true,
                        'condensed' => true,
                        'responsive' => true,
                        'panel' => [
                            'type' => 'primary',
                            'heading' => '<i class="glyphicon glyphicon-list"></i> Список цен и количества работ ',
                            'before'=>'',
                            'after'=>BulkButtonWidget::widget([
                                    'buttons'=>Html::a('<i class="glyphicon glyphicon-trash"></i>&nbsp; Удалить все',
                                        ["placement-bulk-delete"] ,
                                        [
                                            "class"=>"btn btn-danger btn-xs",
                                            'role'=>'modal-remote-bulk',
                                            'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
                                            'data-request-method'=>'post',
                                            'data-confirm-title'=>'Are you sure?',
                                            'data-confirm-message'=>'Are you sure want to delete this item'
                                        ]),
                                ]).
                                '<div class="clearfix"></div>',
                        ]
                    ])?>
                </div>
            </div>
        <?php endif; ?>
    </div>
</div>
<?php Modal::begin([
    "id"=>"progectMainModal",
    "options" => [
        "tabindex" => -1,

    ],
    'size'=>'modal-lg',
    "header"=>"<h3>Основная информация</h3>",
    "footer"=>Html::button('Закрыть',['class'=>'btn btn-primary pull-left','data-dismiss'=>"modal"]).
        Html::button('Сохранить',['class'=>'btn btn-info','type'=>"submit",'onclick'=>"sendAjaxForm()"]),
])?>
<?php Modal::end(); ?>

views/projects/_view-print.php
<div class="projects-form">
    <div class="row">
        <table class="table table-bordered " style="border: 1px solid black">
            <thead>
                <tr>
                    <th colspan="2" class="text-center" style="border: 1px solid black">
                        Маршрутный лист
                    </th>
                </tr>
            </thead>
            <tr>
                <td style="border: 1px solid black">
                    №/ФИО
                </td>
                <td style="border: 1px solid black">
                    Проект: <?=$model->name?>
                </td>
            </tr>
            <tr>
                <td style="border: 1px solid black">
                    План
                </td>
                <td style="border: 1px solid black">
                    Факт
                </td>
            </tr>
            <tr>
                <td style="border: 1px solid black">
                    Зона:
                </td>

                <td style="border: 1px solid black">
                    Зоны сделаны
                </td>
            </tr>
            <tr>
                <td style="border: 1px solid black">
                    Кол-во материалов (листовок) общее: <?=$model->normal?>
                </td>
                <td rowspan="2" style="border: 1px solid black">
                    Кол-во материалов (листовок) сделанное:
                </td>
            </tr>
            <tr>
                <td style="border: 1px solid black">
                    Кол-во домов: <?=$model->count_adress?><br>
                    Кол-во квартир: <?=$model->count_apartament?>
                </td>
            </tr>
            <tr>
                <td style="border: 1px solid black">
                    Кол-во фото общее <?=$model->count_entrance*4+$model->count_adress?><br>
                    Кол-во фото адресов <?=$model->count_adress?> <br>
                    Кол-во фото подъезда (снаружи/внутри) <?=($model->count_entrance*4+$model->count_adress)-$model->count_adress?>
                </td>
                <td style="border: 1px solid black">
                    Кол-во сделанных фото всего:
                </td>
            </tr>
            <tr>
                <td rowspan="2" style="border: 1px solid black">
                    Условные обозначения: <br>
                    Кол-во сделанных листовок - поэтажная расклейка <br>
                    - не было распространения, обязательно указуем причину
                </td>
                <td style="border: 1px solid black">
                    Время начала работы:
                </td>
            </tr>
            <tr>
                <td style="border: 1px solid black">
                    Время окончания работы:
                </td>
            </tr>
            <tr>
                <td width="50%" style="border: 1px solid black">
                    <?=$project->routeTemplates->template?>
                </td>
                <td width="50%" style="border: 1px solid black">
                    <br><br>
                    ОСТАТКИ кол-во _________________ подпись ________________
                    <br><br>
                    ОСТАТКИ принял _________________ подпись ________________

                </td>
            </tr>
        </table>
    </div>
</div>

views/projects/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Projects */

?>
<div class="projects-create">
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
</div>